******************************************************************************************/
public class gitTriggerHandller {
    
    public static void beforeInsert(List<iItemGit> listNewItem){
        
		System.debug('Linha modificada');
       	System.debug('Outra linha editada do git online');
		System.debug('Outra linha editada do git online 1');
		System.debug('Outra linha editada do git online 2');
		System.debug('Outra linha editada do git online 3');
		System.debug('Outra linha editada do git online 4');
    }
	
	public static void novoMetodo(){
		
		System.debug('Outra linha editada do git online 1');
		System.debug('Outra linha editada do git online 2');
	}
	
 
}
