******************************************************************************************/
public class gitTriggerHandller {
    
    public static void beforeInsert(List<iItemGit> listNewItem){
        
		System.debug('Linha modificada');
       	System.debug('Outra linha editada do git online');
		System.debug('Outra linha editada do git online 1');
		System.debug('Outra linha editada do git online 2');
    }
	
	
	public static novoMethod(){
	
		System.debug('Outra linha editada do git online 1');
		System.debug('Outra linha editada do git online 2');
	
	}
 
}
